@ stub TdhAggregatePayloadFilters
@ stub TdhApplyPayloadFilter
@ stub TdhCleanupPayloadEventFilterDescriptor
@ stub TdhCloseDecodingHandle
@ stub TdhCreatePayloadFilter
@ stub TdhDeletePayloadFilter
@ stub TdhEnumerateManifestProviderEvents
@ stub TdhEnumerateProviderFieldInformation
@ stub TdhEnumerateProviderFilters
@ stub TdhEnumerateProviders
@ stub TdhEnumerateRemoveWBEMProviderFieldInformation
@ stub TdhEnumerateRemoteWBEMProviders
@ stub TdhFormatProperty
@ stub TdhGetAllEventsInformation
@ stub TdhGetDecodingParameter
@ stub TdhGetEventInformation
@ stub TdhGetEventMapInformation
@ stub TdhGetManifestEventInformation
@ stub TdhGetProperty
@ stub TdhGetPropertyOffsetAndSize
@ stub TdhGetPropertySize
@ stub TdhGetWppMessage
@ stub TdhGetWppProperty
@ stdcall TdhLoadManifest(wstr)
@ stub TdhLoadManifestFromBinary
@ stub TdhOpenDecodingHandle
@ stub TdhpFindMatchClassFromWBEM
@ stub TdhpGetBestTraceEventInfoWBEM
@ stub TdhQueryProviderFieldInformation
@ stub TdhQueryRemoteWBEMProviderFieldInformation
@ stub TdhSetDecodingParameter
@ stub TdhUnloadManifest
@ stub TdhValidatePayloadFilter
